library/urls.py
"""URLs for library app."""

# Copyright © 2016 SUSE LLC, James Mason <jmason@suse.com>.
#
# This file is part of openbare.
#
# openbare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# openbare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openbare. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^resource/(?P<item_subtype>\w+)/checkout$',
        views.CheckoutView.as_view(),
        name='checkout'
        ),
    url(r'^instance/(?P<primary_key>\d+)/renew$',
        views.renew,
        name='renew'
        ),
    url(r'^instance/(?P<primary_key>\d+)/checkin$',
        views.checkin,
        name='checkin'
        ),
    url(r'^instance/(?P<primary_key>\d+)/request_extension$',
        views.request_extension,
        name='request_extension'
        ),
    url(r'^login/required/$', views.require_login, name='require_login')
]

mailer/urls.py
"""URLS for mailer app."""

# Copyright © 2016 SUSE LLC.
#
# This file is part of openbare.
#
# openbare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# openbare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openbare. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from .views import email_users

app_name = 'mailer'
urlpatterns = [
    url(r'^send/$', email_users, name='email_users'),
]

library/views.py
"""Views used by library app."""

# Copyright © 2016 SUSE LLC, James Mason <jmason@suse.com>.
#
# This file is part of openbare.
#
# openbare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# openbare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openbare. If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.template.defaultfilters import slugify
from django.views.generic.base import TemplateView

import base64
import json
import logging

from .templatetags import formatting_filters
from .models import Lendable
from .models import FrontpageMessage


class IndexView(TemplateView):
    """Display the openbare homepage.

    **Template:**
    :template:`library/home.html`
    """

    template_name = 'library/home.html'

    def get_context_data(self, **kwargs):
        """Return context dictionary for view."""
        context = super(IndexView, self).get_context_data(**kwargs)

        context['resources'] = get_lendable_resources(self.request.user)
        context['user_items'] = get_items_checked_out_by(self.request.user)
        context['checkout'] = False
        context['host'] = settings.HOST
        context['frontpage_messages'] = FrontpageMessage.objects.all()

        return context


def require_login(request):
    """Display warning message if user not authenticated.

    If the user manages to trigger a lendable view in an
    inactive session display a useful message and redirect
    to the index page.
    """
    messages.warning(request, 'Permission denied: You must log in.')
    return redirect(reverse('library:index'))


class CheckoutView(LoginRequiredMixin, IndexView):
    """Checkout :model:`library.Lendable` of item_subtype for user.

    Checkout a lendable of the given item_subtype for the user. The
    user is provided the necessary credentials for the lendable.

    **Template:**
    :template:`library/home.html`
    """

    redirect_field_name = None
    login_url = 'library:require_login'

    def __init__(self):
        """Initialize the view."""
        super(CheckoutView, self).__init__()
        self.item = None

    def get(self, request, *args, **kwargs):
        """Process checkout when view triggered by GET request."""
        logger = logging.getLogger('django')

        try:
            self.item = Lendable(type=self.kwargs.get('item_subtype', None),
                                 user=self.request.user)

            self.item.checkout()
            self.item.save()
        except Exception as e:
            messages.error(request, e)
            logger.exception('%s: %s' % (type(e).__name__, e))
            return redirect(reverse('library:index'))
        else:
            messages.success(
                request,
                "'%s' is checked out to you until %s." %
                (self.item.name,
                 formatting_filters.format_date(self.item.due_on))
            )

        return super(CheckoutView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Return context dictionary for view."""
        context = super(CheckoutView, self).get_context_data(**kwargs)

        context['checkout'] = True
        context['checkout_title'] = self.item.name
        context['checkout_credentials'] = self.item.credentials
        context['download_credentials_payload'] = _pack_up(
            self.item.credentials)
        context['download_credentials_filename'] = _credentials_filename(
            self.item)

        return context


@login_required(redirect_field_name=None, login_url='library:require_login')
def renew(request, primary_key):
    """Renew :model:`library.Lendable` for the length of lending_period_in_days.

    The lendable is renewed and available for another period equal to
    lending_period_in_days. Each lendable can be renewed a given amount
    of times based on the max_renewals value.

    Redirect:
    :view:`library.index`
    """
    item = get_object_or_404(Lendable.all_types,
                             pk=primary_key,
                             user=request.user)
    try:
        item.renew()
    except ValidationError as e:
        for exception_message in e.messages:
            messages.error(request, exception_message)
    except Exception as e:
        messages.error(request, e)
    else:
        messages.success(
            request,
            "'%s' is now due on %s." %
            (item.name, formatting_filters.format_date(item.due_on))
        )
    return redirect(reverse('library:index'))


@login_required(redirect_field_name=None, login_url='library:require_login')
def request_extension(request, primary_key):
    """Send email to admins to request :model:`library.Lendable` extension.

    After renewing a lendable the max available (max_renewals) times
    a user may request an extension. An email is sent to the site
    ADMINS as found in the settings for this request.

    Redirect:
    :view:`library.index`
    """
    admin_path_for_lendable = reverse(
        'admin:library_lendable_change',
        args=(primary_key,)
    )
    admin_url_for_lendable = settings.PRIMARY_URL + admin_path_for_lendable
    try:
        send_mail(
            'openbare: request to extend due_date of PK#%s' % primary_key,
            'Message from %s:\n%s\n\n%s' % (
                request.user.username,
                request.POST['message'],
                admin_url_for_lendable
            ),
            request.user.email,
            _admin_emails()
        )
    except Exception as e:
        messages.error(request, e)
    else:
        messages.success(
            request,
            'Your request was sent to the openbare Admins' +
            ' and will be evaluated.'
        )
    return redirect(reverse('library:index'))


@login_required(redirect_field_name=None, login_url='library:require_login')
def checkin(request, primary_key):
    """Checkin the :model:`library.Lendable`.

    Cleanup and delete Lendable.

    Redirect:
    :view:`library.index`
    """
    item = get_object_or_404(Lendable.all_types,
                             pk=primary_key,
                             user=request.user)
    try:
        item.checkin()
    except Exception as e:
        messages.error(request, e)
    else:
        messages.success(request, "'%s' returned." % (item.name))
    return redirect(reverse('library:index'))


def get_lendable_resources(user):
    """Collect the classes of items that can be checked out.

    Their class and plugin data will be presented as
    a list of resources to 'check out'.
    """
    if not user or user.is_anonymous:
        return []

    resources = []
    for lendable in Lendable.__subclasses__():
        resources.append({
            'name': lendable.name,
            'description': lendable.description,
            'item_subtype': lendable.__name__.lower(),
            'max_checked_out': lendable.max_checked_out,
            'is_available_for_user': lendable.is_available_for_user(user),
            'next_available_date': lendable.next_available_date(),
            'checked_out_items': lendable.all_types.all(),
        })
    return resources


def get_items_checked_out_by(user=None):
    """Return the user's checked out lendables."""
    if not user or user.is_anonymous:
        return []

    return Lendable.all_types.filter(user=user).order_by('checked_out_on')


def _admin_emails():
    return ["%s <%s>" % (admin[0], admin[1]) for admin in settings.ADMINS]


def _pack_up(credentials):
    return base64.urlsafe_b64encode(
        bytes(json.dumps(credentials), encoding="UTF-8")
    )


def _credentials_filename(item):
    return slugify(
        '-'.join([
            "openbare",
            "credentials",
            str(item.pk),
            item.name
        ])
    ) + ".json"

library/templates/library/base.html
{% load staticfiles %}
{% load markdown_deux_tags %}
{% load bootstrap_filters %}

{% comment %}
# Copyright © 2016 SUSE LLC, James Mason <jmason@suse.com>.
#
# This file is part of openbare.
#
# openbare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# openbare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openbare. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
      openbare - {% block title %}Public Cloud Demo Account Library{% endblock %}
    </title>
    <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">
    <!-- Bootstrap + bootswatch 'yeti' theme -->
    <link href="{% static 'css/open-sans-font.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- Font Awesome icons -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <!-- custom CSS -->
    <link href="{% static 'css/openbare.css' %}" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <!-- Header (navigation bar) -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">openbare</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user and user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.get_full_name|default:user.username }}<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  {% if user.is_superuser or user.is_staff %}
                    <li><a href="/admin"><i class="fa fa-key"></i>Admin Site</a></li>
                    <li><a href="{% url 'mailer:email_users' %}"><i class="fa fa-envelope-o"></i>Email Users</a></li>
                  {% endif %}
                  <li><a href="{% url 'auth:logout' %}?next=/"><i class="fa fa-sign-out"></i>Logout</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{% url 'social:begin' 'opensuse' %}?next={{ request.path }}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {{ message.level | bootstrap_alert_class }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block main %}{% endblock %}
      <!-- Footer -->
      <div class="footer">
        <nav class="navbar navbar-default navbar-fixed-bottom">
          <div class="container">
            <p class="navbar-text">Copyright &copy; 2016 SUSE</p>
            <p class="navbar-text"><a href="#" class="navbar-link" data-toggle="modal" data-target="#credits-modal">Attributions</a></p>
            <p class="navbar-text navbar-right"><a href="#top" class="navbar-link">Back to top</a></p>
          </div>
        </nav>
      </div>
    </div>
    <!-- Credits Modal -->
    <div class="modal fade" id="credits-modal" tabindex="-1" role="dialog" aria-labelledby="creditsModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Credits</h4>
          </div>
          <div class="modal-body">
            <dl>
              <dt><a href="{% static 'images/sources/Бібліотека_Амстердаму.JPG' %}">Cover photo</a></dt>
              <dd>
                By Anntinomy (Own work) [<a href="http://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>], <a href="https://commons.wikimedia.org/wiki/File%3A%D0%91%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_%D0%90%D0%BC%D1%81%D1%82%D0%B5%D1%80%D0%B4%D0%B0%D0%BC%D1%83.JPG">via Wikimedia Commons</a>
              </dd>
              <dt><a href="http://bootswatch.com/yeti/">'Yeti' theme</a></dt>
              <dd>
                Made by <a href="http://thomaspark.co" rel="nofollow">Thomas Park</a>. Contact him at <a href="mailto:thomas@bootswatch.com">thomas@bootswatch.com</a><br/>
                Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/gh-pages/LICENSE">MIT License</a>.<br/>
                Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts" rel="nofollow">Google</a>.
              </dd>
            </dl>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    {% block js %}{% endblock %}
  </script>
  {% block js_include %}{% endblock %}
</html>

library/templates/library/home.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% load markdown_deux_tags %}
{% load formatting_filters %}

{% comment %}
# Copyright © 2016 SUSE LLC, James Mason <jmason@suse.com>.
#
# This file is part of openbare.
#
# openbare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# openbare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openbare. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block main %}
  <div class="jumbotron openbare-background">
    <h1>openbare</h1>
    <p>
      Public Cloud Demo Account Library
    </p>
    {% if not user or user.is_anonymous %}
    <p>
      {% for backend in backends.backends %}
        <a class="btn btn-success btn-lg" href="{% url 'social:begin' backend %}?next={{ request.path }}"><i class="fa fa-sign-in"></i>Login via {{ backend }}</a>
      {% endfor %}
    </p>
    {% endif %}
  </div>

  {% if not user or user.is_anonymous %}
    <div class="row">
      <div class="col-md-12">
        <h2>Welcome!</h2>
        <dl>
          {% for message in frontpage_messages %}
            <dt>{{ message.title }}</dt>
            <dd>{{ message.body|linebreaks }}</dd>
          {% endfor %}
          <dt>License</dt>
          <dd>
            <i>openbare</i> is licensed under the GPL v3 license. Please file issues or send contributions on GitHub: <a href="https://github.com/openbare/openbare">https://github.com/openbare/openbare</a>.
          </dd>
        </dl>
      </div>
    </div>
  {% endif %}


  {% if user and user.is_authenticated %}
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Library resources</h3>
          </div>
          <div class="panel-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Resource</th>
                  <th>Available?</th>
                </tr>
              </thead>
              <tbody>
              {% for resource in resources %}
                <tr>
                  <td>
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#resource_{{ resource.item_subtype }}_details">{{ resource.name }}</button>
                  </td>
                  <td>
                    {% if resource.is_available_for_user %}
                      <a href="{%url 'library:checkout' resource.item_subtype %}" role="button" class="btn btn-default btn-xs" title="Grant yourself access to this resource for a limited time." data-toggle="tooltip" >Checkout</a>
                    {% else %}
                      Due on {{ resource.next_available_date|format_date }}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Checked out to me</h3>
          </div>
          <div class="panel-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Resource</th>
                  <th colspan=3>Due date</th>
                </tr>
              </thead>
              <tbody>
              {% for checked_out_item in user_items %}
                <tr>
                  <td>
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#item_{{ checked_out_item.pk }}_details">{{ checked_out_item.name }}</button>
                  </td>
                  <td>
                    {{ checked_out_item.due_on|format_date }}
                  </td>
                  <td class="text-right">
                    {% if checked_out_item.is_renewable %}
                      <a href="{%url 'library:renew' checked_out_item.pk %}" role="button" class="btn btn-default btn-xs" title="Need more time? Extend the due date." data-toggle="tooltip">Renew</a>
                    {% else %}
                      <span title="Need more time? Ask the site admins for an extension" data-toggle="tooltip"><button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#item_{{ checked_out_item.pk }}_request_extension" >Request Extension</button></span>
                    {% endif %}
                  </td>
                  <td class="text-right">
                    <a href="{%url 'library:checkin' checked_out_item.pk %}" role="button" class="btn btn-default btn-xs checkin-btn" title="Finished early? Return the resource so it's available to others." data-toggle="tooltip">Return</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {% for resource in resources %}
      <div class="modal fade" id="resource_{{ resource.item_subtype }}_details" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">{{ resource.name }}</h4>
            </div>
            <div class="modal-body">
              {{ resource.description|markdown }}
              <table class="table">
                <caption>{{ resource.checked_out_items.count }} of {{ resource.max_checked_out }} are checked out.</caption>
                <thead>
                  <tr>
                    <th>To</th>
                    <th>Due date</th>
                    <th>Renewable?</th>
                  </tr>
                </thead>
                <tbody>
                  {% for checked_out_item in resource.checked_out_items %}
                    <tr>
                      <td>
                        {{ checked_out_item.user }}
                      </td>
                      <td>
                        {{ checked_out_item.due_on }}
                      </td>
                      <td>
                        {% if checked_out_item.is_renewable %}
                          <i class="fa fa-check"></i>
                        {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="modal-footer">
              {% if resource.is_available_for_user %}
                <a href="{%url 'library:checkout' resource.item_subtype %}" role="button" class="btn btn-default" data-placement="left" title="Grant yourself access to this resource for a limited time." data-toggle="tooltip">Checkout</a>
              {% else %}
                <button class="btn btn-disabled" data-toggle="tooltip" data-placement="left" title="Not available. Due back on {{ resource.next_available_date|format_date }}.">Checkout</button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}

    {% for checked_out_item in user_items %}
      <div class="modal fade" id="item_{{ checked_out_item.pk }}_request_extension" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <form action="{%url 'library:request_extension' checked_out_item.pk %}" method="POST">
              {% csrf_token %}
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">
                  {{ checked_out_item }} - request extension
                </h4>
              </div>
              <div class="modal-body">
                <p>
                  If you need to keep this resource beyond the due date, you may
                  request an extension from the Administrators.
                </p>
                <p>
                  Please explain your request here:
                </p>
                <textarea name="message" class="form-control" rows="5"></textarea>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary" title="Email your request to the site admins" data-placement="left" data-toggle="tooltip">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>



      <div class="modal fade" id="item_{{ checked_out_item.pk }}_details" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">
                {{ checked_out_item }}
              </h4>
            </div>
            <div class="modal-body">
              <dl>
                <dt>Checked out on:</dt>
                <dd>
                  {{ checked_out_item.checked_out_on|format_date }}
                </dd>
                <dt>Available renewals:</dt>
                <dd>
                  {{ checked_out_item.renewals }}
                </dd>
                <dt>Current due date:</dt>
                <dd>
                  {{ checked_out_item.due_on|format_date }}
                </dd>
              </dl>
            </div>
            <div class="modal-footer">
              {% if checked_out_item.is_renewable %}
                <a href="{%url 'library:renew' checked_out_item.pk %}" role="button" class="btn btn-default btn-xs" data-placement="left" title="Need more time? Extend the due date." data-toggle="tooltip">Renew</a>
              {% else %}
                <span title="Need more time? Ask the site admins for an extension" data-toggle="tooltip"><button type="button" class="btn btn-default btn-xs" data-dismiss="modal" data-toggle="modal" data-target="#item_{{ checked_out_item.pk }}_request_extension" >Request Extension</button></span>
              {% endif %}
              <a href="{%url 'library:checkin' checked_out_item.pk %}" role="button" class="btn btn-default btn-xs checkin-btn" data-placement="left" title="Finished early? Return the resource so it's available to others." data-toggle="tooltip">Return</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    {% if checkout %}
      <div class="modal fade" id="checkout_credentials" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">
                {{ checkout_title }}
              </h4>
            </div>
            <div class="modal-body">
              <p>
                Here are the credentials for accessing your instance:
              </p>
              <dl>
                {% for label, value in checkout_credentials.items %}
                  <dt>{{ label }}</dt>
                  <dd>
                    <code>{{ value }}</code>
                  </dd>
                {% endfor %}
              </dl>
              <p>
                Be sure to
                <a href="data:application/json;base64,{{ download_credentials_payload }}" target="_blank" download="{{ download_credentials_filename }}">
                  download
                </a>
                or otherwise record these before closing this dialog, they cannot be presented again.
                If you lose these credentials, you will have to return this item, and checkout the resource again.
              </p>
            </div>
            <div class="modal-footer">
              <a href="data:application/json;base64,{{ download_credentials_payload }}" target="_blank" download="{{ download_credentials_filename }}" role="button" class="btn btn-default">Download Credentials</a>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  {% endif %}
  <div id="grey-out" style="position:fixed; z-index: 1051; top:0; left:0; bottom:0; right:0; background:rgba(0,0,0,.5); display: none;"></div>
{% endblock %}

{% block js_include %}
  {% if checkout %}
    <script src="{% static 'js/checkout.js' %}"></script>
  {% endif %}
  <script src="{% static 'js/checkin.js' %}"></script>
{% endblock %}